### PR TITLE
Hand component

### PR DESCRIPTION
**Pull request by sidhlee**
Also added settings.json inside .vscode folder to disable format on save.

### CODE REVIEW

**Comment by sidhlee** [comment]
closed by mistake

**Review by raidnaji — COMMENTED** [review]
Now that you have created the "Hand" component, should you add that to the return in App.js and pass in 'cards' as a prop?

**Comment by sidhlee** [comment]
> Now that you have created the "Hand" component, should you add that to the return in App.js and pass in 'cards' as a prop?

I think both Dealer and Player components are wrapping around Hand component, so will have to built them first and pass cards into them, which then in turn pass cards into Hand

**Review by evankwan — APPROVED** [review]
Looks all good to me. Hand component doesn't need to be added to App.js yet as it will live in the Player/Dealer components.

**Comment by raidnaji** [comment]
> > Now that you have created the "Hand" component, should you add that to the return in App.js and pass in 'cards' as a prop?
> 
> I think both Dealer and Player components are wrapping around Hand component, so will have to built them first and pass cards into them, which then in turn pass cards into Hand

Yup, that makes sense. Thanks for clarifying. Approved.

**Review by raidnaji — APPROVED** [review]

**Pull request merged**
